[template]
include = ["README.md", "Cargo.toml", "cliff.toml", "src/"]
# include and exclude are exclusive, if both appear we will use include
exclude = ["revise.toml"]

[placeholders]
github-username = { prompt = "Enter git username", type = "string" }
github-repository = { prompt = "Enter git repository", type = "string" }
crate-description = { prompt = "Enter crate description", type = "string" }
repository_url = "https://github.com/{{github-username}}/{{github-repository}}"