[template]
include = ["README.md", "Cargo.toml", "src/"]
# include and exclude are exclusive, if both appear we will use include
exclude = ["revise.toml"]

[placeholders]
git-user-name = { prompt = "Enter git username", type = "string" }
git-repository-name = { prompt = "Enter git repository", type = "string" }
