[placeholders]
github-username = { prompt = "Enter git username", type = "string" }
github-repository = { prompt = "Enter git repository", type = "string" }
crate-description = { prompt = "Enter crate description", type = "string" }

[template]
include = ["Cargo.toml", "README.md", "src/"]
exclude = ["cliff.toml"]